### ISSUE TITLE
회원가입 페이지 구성

### ISSUE THREAD

**Issue by prkgnt** [Flint-org/Flint-Front#2]
## 작업할 내용
- [x] 리액트 네비게이션 설치
- [ ] 폰트 적용
- [x] 리액트 네이비게이션 적용
- [x] 스플래시 스크린
- [x] 회원가입 페이지 고정 헤더 생성
### SNS(카카오, 네이버) 로그인 페이지
- [x] 데이터 처리 전까지 완료
- [ ] 데이터 처리 완료
### 학과, 학번, 입학년도 선택 페이지 
- [x] 데이터 처리 전까지 완료
- [ ] 데이터 처리 완료
### 이메일 입력 페이지
- [x] 데이터 처리 전까지 완료
- [ ] 데이터 처리 완료
### 인증번호 입력 페이지 
- [x] 데이터 처리 전까지 완료
- [ ] 데이터 처리 완료
### 인증서 첨부 페이지
- [x] 데이터 처리 전까지 완료
- [ ] 데이터 처리 완료

**Comment by 2-hs2** [comment]
### 20230811(금) 진행한 작업

1. 회원가입에 필요한 페이지별로 컴포넌트 생성
2. 시작하기 페이지를 제외한 페이지들에 고정으로 들어가는 헤더 컴포넌트 생성 후 각 페이지에 적용

**Comment by 2-hs2** [comment]
모달 텍스트 자간 조절 필요
- [ ] 완료 여부
